# Generated by Django 2.0.3 on 2018-03-28 18:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20180324_2316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kurs',
            new_name='Post',
        ),
    ]
